// PDF Export Utilities using jsPDF
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { Splice, Project, Enclosure, LossBudgetResult } from "@/types";
import { getSpliceComplianceStatus, calculateSpliceStats } from "@/lib/spliceUtils";

// ============================================
// SPLICE REPORT PDF
// ============================================

interface SpliceReportData {
  project?: Project;
  enclosure?: Enclosure;
  splices: Splice[];
  generatedBy?: string;
}

export function generateSpliceReportPDF(data: SpliceReportData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("Splice Documentation Report", pageWidth / 2, 20, { align: "center" });

  // Project Info
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  let y = 35;

  if (data.project) {
    doc.text(`Project: ${data.project.name}`, 14, y);
    y += 7;
    doc.text(`Location: ${data.project.location}`, 14, y);
    y += 7;
  }

  if (data.enclosure) {
    doc.text(`Enclosure: ${data.enclosure.name}`, 14, y);
    y += 7;
    if (data.enclosure.address) {
      doc.text(`Address: ${data.enclosure.address}`, 14, y);
      y += 7;
    }
  }

  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, y);
  y += 7;

  if (data.generatedBy) {
    doc.text(`Generated By: ${data.generatedBy}`, 14, y);
    y += 7;
  }

  // Statistics
  const stats = calculateSpliceStats(data.splices);
  y += 5;
  doc.setFont("helvetica", "bold");
  doc.text("Summary Statistics", 14, y);
  y += 7;
  doc.setFont("helvetica", "normal");

  const statsText = [
    `Total Splices: ${stats.total}`,
    `Completed: ${stats.completed}`,
    `Pending: ${stats.pending}`,
    `Average Loss: ${stats.avgLoss > 0 ? stats.avgLoss.toFixed(2) + " dB" : "N/A"}`,
    `Pass Rate: ${stats.passRate.toFixed(1)}%`,
  ];

  statsText.forEach((text) => {
    doc.text(text, 14, y);
    y += 6;
  });

  y += 10;

  // Splice Table
  const tableData = data.splices.map((splice) => {
    const compliance = getSpliceComplianceStatus(splice);
    return [
      `${splice.fiberA}`,
      `${splice.tubeAColor}/${splice.fiberAColor}`,
      `${splice.fiberB}`,
      `${splice.tubeBColor}/${splice.fiberBColor}`,
      splice.spliceType,
      splice.loss !== undefined ? splice.loss.toFixed(2) : "-",
      compliance.status.toUpperCase(),
      splice.technicianName || "-",
    ];
  });

  autoTable(doc, {
    startY: y,
    head: [
      [
        "Fiber A",
        "Color A",
        "Fiber B",
        "Color B",
        "Type",
        "Loss (dB)",
        "Status",
        "Tech",
      ],
    ],
    body: tableData,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [59, 130, 246] },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    columnStyles: {
      5: { halign: "right" },
      6: { halign: "center" },
    },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
    doc.text(
      "Generated by NetLink OSP Fiber Management",
      14,
      doc.internal.pageSize.getHeight() - 10
    );
  }

  // Download
  const filename = data.enclosure
    ? `splice_report_${data.enclosure.name.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.pdf`
    : `splice_report_${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(filename);
}

// ============================================
// LOSS BUDGET REPORT PDF
// ============================================

export function generateLossBudgetPDF(budget: LossBudgetResult): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("Loss Budget Report", pageWidth / 2, 20, { align: "center" });

  // Budget Name
  doc.setFontSize(14);
  doc.text(budget.input.name, pageWidth / 2, 30, { align: "center" });

  let y = 45;

  // Parameters Section
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Link Parameters", 14, y);
  y += 10;

  doc.setFont("helvetica", "normal");
  const params = [
    ["Fiber Type", budget.input.fiberType],
    ["Wavelength", `${budget.input.wavelength} nm`],
    ["Distance", `${budget.input.distanceKm} km`],
    ["Fusion Splices", `${budget.input.fusionSplices}`],
    ["Mechanical Splices", `${budget.input.mechanicalSplices}`],
    ["Connector Pairs", `${budget.input.connectorPairs}`],
    ["Connector Type", budget.input.connectorType],
    ["Safety Margin", `${budget.input.marginDb} dB`],
  ];

  params.forEach(([label, value]) => {
    doc.text(`${label}:`, 14, y);
    doc.text(value, 80, y);
    y += 7;
  });

  y += 10;

  // Loss Breakdown Section
  doc.setFont("helvetica", "bold");
  doc.text("Loss Breakdown", 14, y);
  y += 10;

  autoTable(doc, {
    startY: y,
    head: [["Component", "Loss (dB)"]],
    body: [
      ["Fiber Attenuation", budget.fiberLoss.toFixed(2)],
      ["Fusion Splice Loss", budget.fusionLoss.toFixed(2)],
      ["Mechanical Splice Loss", budget.mechanicalLoss.toFixed(2)],
      ["Connector Loss", budget.connectorLoss.toFixed(2)],
      ["Safety Margin", budget.marginLoss.toFixed(2)],
    ],
    foot: [["TOTAL LOSS", budget.totalLoss.toFixed(2)]],
    styles: { fontSize: 10 },
    headStyles: { fillColor: [59, 130, 246] },
    footStyles: { fillColor: [34, 197, 94], fontStyle: "bold" },
    columnStyles: {
      1: { halign: "right" },
    },
  });

  // Footer
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    14,
    doc.internal.pageSize.getHeight() - 15
  );
  doc.text(
    "Generated by NetLink OSP Fiber Management",
    14,
    doc.internal.pageSize.getHeight() - 10
  );

  // Download
  const filename = `loss_budget_${budget.input.name.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(filename);
}

// ============================================
// INVENTORY REPORT PDF
// ============================================

import type { InventoryItem } from "@/types";

export function generateInventoryReportPDF(items: InventoryItem[]): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("Inventory Report", pageWidth / 2, 20, { align: "center" });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 30);
  doc.text(`Total Items: ${items.length}`, 14, 36);

  // Low stock count
  const lowStock = items.filter((i) => i.quantity <= i.minStock);
  if (lowStock.length > 0) {
    doc.setTextColor(220, 38, 38);
    doc.text(`Low Stock Items: ${lowStock.length}`, 14, 42);
    doc.setTextColor(0, 0, 0);
  }

  // Table
  const tableData = items.map((item) => [
    item.category,
    item.name,
    item.partNumber || "-",
    `${item.quantity} ${item.unit}`,
    `${item.minStock}`,
    item.quantity <= item.minStock ? "LOW" : "OK",
    item.location || "-",
  ]);

  autoTable(doc, {
    startY: 50,
    head: [["Category", "Name", "Part #", "Qty", "Min", "Status", "Location"]],
    body: tableData,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [59, 130, 246] },
    didParseCell: function (data) {
      // Highlight low stock rows
      if (data.section === "body" && data.column.index === 5) {
        if (data.cell.raw === "LOW") {
          data.cell.styles.textColor = [220, 38, 38];
          data.cell.styles.fontStyle = "bold";
        } else {
          data.cell.styles.textColor = [34, 197, 94];
        }
      }
    },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  // Download
  doc.save(`inventory_report_${new Date().toISOString().split("T")[0]}.pdf`);
}
